### ISSUE TITLE
write_canonical/[1,2] too defensive in quoting atoms

### ISSUE THREAD

**Issue by jburse** [tau-prolog/tau-prolog#100]
Hi, was playing around with write family predicates. 
Nice that the output is shown inline in the sandbox!

But I have the feeling that the predicate is too defensive
since it always quotes atoms:

```
?- writeq(a=..b).
true.
a =.. b
?- write_canonical(a=..b).
true.
'=..'(a, b)
```

My expectation is rather:

```
?- writeq(a=..b).
true.
a =.. b
?- write_canonical(a=..b).
=..(a, b)
true.
```
writeq/[1,2] and write_canonical/[1,2] are similar according 
to ISO core standard, they should use quoted(true). Any particular 

reason to always quote atoms in write_canonical/[1,2]?

**Comment by jburse** [comment]
Here is a screenshot for proof, and also you see the version:

![grafik](https://user-images.githubusercontent.com/5411487/73595204-127cfe80-4516-11ea-9580-85a6713a1bb1.png)

**Comment by jariazavalverde** [comment]
You're right, I wasn't considering graphic tokens in the regex which verifies whether quotes are needed. Thanks for your report.
