### ISSUE TITLE
Compatibility with React.js

### ISSUE THREAD

**Issue by hsjsjsj009** [tau-prolog/tau-prolog#114]
Anybody know how to fix this error? 
It came when i use tau prolog as ai engine in my react app.
![Screenshot from 2020-03-17 08-32-55](https://user-images.githubusercontent.com/47316759/76814202-b99ac880-682c-11ea-85f7-c27282146ab7.png)
![Screenshot from 2020-03-17 08-53-34](https://user-images.githubusercontent.com/47316759/76814240-d0d9b600-682c-11ea-9aca-cb8c005d12b2.png)

Thanks.

**Comment by gilbert** [comment]
That's not related to react, `fs.existsSync` is a node module. Perhaps you're using the node version of tau instead of the browser version?

**Comment by hsjsjsj009** [comment]
How can i use tau browser version in react app? It always detect my code as node modules.

**Comment by gilbert** [comment]
Check out the [downloads page](http://tau-prolog.org/downloads).

**Comment by jariazavalverde** [comment]
Browser and Node.js versions are the same. This is how Tau Prolog detects if the code is running in Node.js or in the browser:

```javascript
var nodejs_flag = typeof module !== 'undefined' && module.exports !== undefined;
```

In any case, I'll add an option so you can force the environment.

**Comment by hsjsjsj009** [comment]
Ok thank you

**Comment by yves91300** [comment]
Hello,
I try to learn tau-prolog / node / reactjs. And i have exactly the same problem hsjsjsj009 initialy reported :  "TypeError: fs.existsSync is not a function".
Did you solve it ? What should i do pratically ?

**Comment by skykanin** [comment]
Any update on this? I'm also trying to use the npm package in the browser, but it's depending on internal nodejs stuff like `fs.existsSync`. Would be nice if there was a way to force the environment

**Comment by gilbert** [comment]
It depends on how you're using the module. If you're using something like browserify or webpack, unfortunately Tau thinks it's running in nodejs [due to this line](https://github.com/tau-prolog/tau-prolog/blob/master/modules/core.js#L2782).

Actually, let me push up a quick PR to fix this.

**Comment by meesern** [comment]
The problem is the way core.js detects a node environment.  React uses modules so the line:

    var nodejs_flag = typeof module !== 'undefined' && module.exports !== undefined;

Sets nodejs_flag true even though it's a browser environment (and fs.existsSync doesn't exist).  I believe this test is better:

    var nodejs_flag=new Function("try {return this===global;}catch(e){return false;}")();

**Comment by hsjsjsj009** [comment]
I think it's better if there is a flag to force read as program or file_name.

**Comment by meesern** [comment]
Would mean an extra step to use with react though right?  Might it work to do both (auto if flag undefined).

**Comment by hsjsjsj009** [comment]
Yes

**Comment by hsjsjsj009** [comment]
Actually i've tweaked the code in local, if the string end with dots ('.') it will detect as program else it will detect as file_name

**Comment by meesern** [comment]
Cool!
