### ISSUE TITLE
toJavascript on atoms changed behavior

### ISSUE THREAD

**Issue by arcanis** [tau-prolog/tau-prolog#122]
In 0.2.66 calling `toJavascript` on an atom would yield the following:

```
foo
@foo/bar
```

Now it yields the following:

```
foo
'@foo/bar'
```

As you can see, it seems that atoms are escaped before being returned to Javascript (I suspect they're actually always stored escaped in `this.id`). Is this expected?

**Comment by jariazavalverde** [comment]
Yes, this is expected. `_.prototype.toJavaScript` uses `_.prototype.toString` for variables, numbers and atoms.

Perhaps it may be interesting to add an optional parameter in `_.prototype.toJavaScript` to set the term writing options (**quoted**, **ignore_ops** and **numbervars**):

http://tau-prolog.org/documentation/prolog/builtin/write_term/2

Please, let me know if you are interested in that.

**Comment by jariazavalverde** [comment]
From the next release (v0.3.0), the default value for `quoted` will be `false`. Anyway, you can explicitly set this option:

```javascript
var term = new pl.type.Term("@foo/bar");
console.log(term.toJavaScript()); // @foo/bar
console.log(term.toJavaScript({quoted: false})); // @foo/bar
console.log(term.toJavaScript({quoted: true})); // '@foo/bar'

```

**Comment by arcanis** [comment]
Perfect, thanks! 😀
