### ISSUE TITLE
Missing standard predicate_property/2 predicate

### ISSUE THREAD

**Issue by pmoura** [tau-prolog/tau-prolog#126]
Would it be possible to add the standard `predicate_property/2` predicate? Ideally, the following properties would be supported:

- `built_in`
- `static`
- `dynamic`
- `multifile`
- `meta_predicate(Template)`

For sample calls and tests, please check:
https://github.com/LogtalkDotOrg/logtalk3/blob/master/tests/prolog/predicates/predicate_property_2/tests.lgt

**Comment by pmoura** [comment]
Thanks for implementing this key reflection predicate in record time!

**Comment by jariazavalverde** [comment]
This still needs some revision due to meta predicates, given that `meta_predicate/1` is not currently defined in Tau Prolog.

**Comment by pmoura** [comment]
Noted. But the `meta_predicate(Template)` property is also useful for built-in meta-predicates, specially non-standard ones, as it allows an application to query of a predicate is a meta-predicate and act accordingly. E.g. a tool that performs code analysis or a tool that constructs a cross-referencing diagram.
