### ISSUE TITLE
Missing predicate to query environment variables

### ISSUE THREAD

**Issue by pmoura** [tau-prolog/tau-prolog#127]
The new `library(os)` is missing a predicate to query environment variables. A common name among Prolog systems is `environ/2`. Of course, `environment_variable/2` would be cleaner and clear even if more verbose.

**Comment by jariazavalverde** [comment]
The following predicates have been added to the `os` module:

* `getenv/2`
* `setenv/2`
* `unsetenv/1`

`getenv(Name, Value)` returns all environment variables on backtracking if `Name` is a variable.
