### ISSUE TITLE
Missing predicate to query the operating-system for a timestamp

### ISSUE THREAD

**Issue by pmoura** [tau-prolog/tau-prolog#129]

**Comment by pmoura** [comment]
The new library(os) is missing a predicate to query  the operating-system for a timestamp. Not really a common name for such a predicate among Prolog systems. A second predicate to query the current time (hours, minutes, seconds) and date (year, month, day) would also be useful.

**Comment by jariazavalverde** [comment]
This predicate is currently available in the core library: `get_time/1` (#95) returns the number of milliseconds elapsed since January 1, 1970, 00:00:00 UTC. I just see I didn't add it to the doc. 🤦‍♂️

**Comment by pmoura** [comment]
Good 🙂 I will update the Logtalk adapter file accordingly.
