### ISSUE TITLE
Odd existence error for the (;)/2 control construct

### ISSUE THREAD

**Issue by pmoura** [tau-prolog/tau-prolog#132]
With the following code (in a consulted source file):

```prolog
logtalk_library_path(logtalk_home, '$LOGTALKHOME/').

% Logtalk user directory
logtalk_library_path(logtalk_user, '$LOGTALKUSER/').

% user home directory
logtalk_library_path(home, HOME) :-
	(	getenv('HOME', _) ->
		% likely a POSIX system but Windows users
		% may also define this environment variable
		HOME = '$HOME/'
	;	getenv('USERPROFILE', _) ->
		% Windows systems define this environment variable
		HOME = '$USERPROFILE/'
	;	fail
	).
```

And with the query:

```prolog
logtalk_library_path(Library,_).
```

I get:

```bash
$ node ./tp.js 
Library = logtalk_home ;
Library = logtalk_user ;
uncaught exception: error(existence_error(procedure, /(;, 2)), /(logtalk_library_path, 2))
false.
```

The file compiles fine without any warnings or errors in  the sandbox in the Tau Prolog website.

**Comment by jariazavalverde** [comment]
What version of Tau Prolog are you using? I get the following output  in Node.js (Tau v0.3.0):

```prolog
Library = logtalk_home ;
Library = logtalk_user ;
Library = home ;
false.
```

**Comment by pmoura** [comment]
I followed your advice by using `npm` to install the current release version of Tau Prolog and then replaced the modules with a copy from the current git version (`master` branch). Possible that I did some mistake.

**Comment by pmoura** [comment]
Found the cause. Changing the code above by commenting the last `require`:

```js
//require("./node_modules/tau-prolog/modules/system.js")(pl);
```

Allows the query to give all expected answers.

**Comment by jariazavalverde** [comment]
I see the problem. Please remove the `system` package. Now built-in predicates are stored in a module callled `system`. The `system` package, which is a package under construction that must be renamed, is replacing the builtin predicates.

**Comment by pmoura** [comment]
Thanks for the quick reply. Closing.
