### ISSUE TITLE
Web Worker support

### ISSUE THREAD

**Issue by goshdarngames** [tau-prolog/tau-prolog#136]
I am seeking some advice on whether running tau-prolog inside a web worker ( multi threading ) is supported.

I made the following changes to the tau-prolog.js file I downloaded ( I selected only the core and lists modules):

```
210c210
<                               text = self.prompt();
---
>                               text = window.prompt();
2309a2310,2315
>                       if( this.get_flag("nodejs").indicator === "false/0" && program != "" && document.getElementById( string ) ) {
>                               var script = document.getElementById( string );
>                               var type = script.getAttribute( "type" );
>                               if( type !== null && type.replace( / /g, "" ).toLowerCase() === "text/prolog" ) {
>                                       string = script.text;
>                               }
2311c2317
<                       if( this.get_flag("nodejs").indicator === "true/0" ) {
---
>                       } else if( this.get_flag("nodejs").indicator === "true/0" ) {
2924c2930
<               __env: nodejs_flag ? global : self,
---
>               __env: nodejs_flag ? global : window,
7094c7100
<               self.pl = pl;
---
>               window.pl = pl;
```

I just replaced instances of 'window' with 'self' and removed a conditional that referenced the 'document'.  Web Workers do not have access to the document and use 'self' for the global namespace instead of 'window'.

Is it really that simple?  Should I expect further trouble down the line with this approach?

I'm planning to use this in order to run long queries in the background without the user interface locking up.  Is this even necessary?  I am running the prolog system inside a game and it's necessary to keep updating the canvas with 'request animation frame' while prolog works.  I know tau-prolog uses callbacks to get answers asynchronously so I'm not certain if there's any benefit to using a web worker.

The benefit I could see would be if I were to a particularly heavy query ( I am planning on using a recursive backtracking algorithm ) then that could potentially freeze the main event thread.

**Comment by jariazavalverde** [comment]
> Is it really that simple? Should I expect further trouble down the line with this approach?

If it works for you right now, you shouldn't have other problems in future versions.

> The benefit I could see would be if I were to a particularly heavy query ( I am planning on using a recursive backtracking algorithm ) then that could potentially freeze the main event thread.

There is a predicate `sleep/1` in the `system` package (this package it is not officially published and will be renamed in the next release) that can prevent the browser from freezing. I used it in the example of the knight's tour, sleeping the thread one millisecond after each jump:

http://tau-prolog.org/examples/knights-tour

```prolog
tour(Position, Visited, N, Tour) :-
	fill_cell(Position, N),
	jump(Position, Next),
	sleep(1),
	M is N+1,
	\+(member(Next, Visited)),
	( tour(Next, [Position|Visited], M, Tour) ; 
	  fill_cell(Next, ''), fail).
```

This may be helpful to you.

**Comment by pmoura** [comment]
Good to know that `sleep/1` is already implemented! It would make sense to move it to `library(os)`?

**Comment by goshdarngames** [comment]
Thanks for your answer - the sleep predicate would help with my goals.  

Something else I'm considering is allowing the user to cancel long-running queries so I think the way to do that would be to use 'sleep' and then immediately after check a predicate for some message from the user and call 'halt' if so.

The alternative approach is to run each query in its own worker thread and then call terminate() on the thread to cancel the query.  Spawning and killing threads like this seems a little heavy handed - but at the same time I like the idea of keeping this 'cancel query' out of the prolog script.

I'm working on a 'puzzle editor' for a game and my plan is that as the user makes changes to the puzzle the prolog system checks the puzzle is valid.  I am debating if the prolog system should run every time they make a change and give real time feedback or if the prolog system should sleep until they click 'verify' and then work out the answer.  If the user changes the puzzle while the checker is running then any work it has done already will need to be discarded.

Anyway - thanks again for your help.  I'm looking forward to playing around with prolog in the browser!
