### ISSUE TITLE
read_term/3 fails to read and return the end_of_file term

### ISSUE THREAD

**Issue by pmoura** [tau-prolog/tau-prolog#139]
The `read_term/3` predicate fails to read and return the `end_of_file` term. For example, consider the file `foo` with the contents (with a empty line at the end to ensure a layout character):

```prolog
bar.

```

Then try:

```js
session.consult( "foo(Stream,Term1,Term2) :- open(foo,read,Stream), read_term(Stream,Term1,[]), writeq(Term1), nl, read_term(Stream,Term2,[])." );
session.query( "foo(Stream,Term1,Term2)." );
```

The process hangs. But the expected results are:

```bash
bar
Stream = <stream>(2), Term1 = bar, Term2 = end_of_file ;
false.
```

Instead, the process hangs after printing the first term.

**Comment by jariazavalverde** [comment]
This should be reviewed in the future. I'm not entirely convinced of my `EOF` detection in Node.js with `readSync`. But for now, it works and  I can't find another solution. :neutral_face:

**Comment by pmoura** [comment]
Thanks for the quick fix. Testing show it working as expected in the context of Logtalk loading and startup (which is still failing at a later point; debugging).
