### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by pmoura** [tau-prolog/tau-prolog#144]
I'm getting the following error during Logtalk startup while compiling one of its built-in objects:

```bash
/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:1943
	Term.prototype.rename = function( thread ) {
	                                ^

RangeError: Maximum call stack size exceeded
    at Term.rename (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:1943:34)
    at Term.rename (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:1977:27)
    at Term.rename (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:1977:27)
    at Term.rename (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:1977:27)
    at Term.rename (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:1977:27)
    at Term.rename (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:1977:27)
    at Term.rename (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:1977:27)
    at Term.rename (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:1977:27)
    at Term.rename (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:1977:27)
    at Term.rename (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:1977:27)
```

I tried bumping session limit to increasing large values like:

```js
var session = pl.create( 6400000 );
```

but still get the same error. Can the limit being exceeded be increased?

**Comment by jariazavalverde** [comment]
That limit is imposed by JavaScript (Node.js) and cannot be increased. Could you tell me what term is being renamed when that error occurs? An infinite recursion error would be strange, since Tau Prolog cannot create terms with circular references like:

```javascript
var term = new pl.type.Term("p");
term.args.push(term);
```

**Comment by pmoura** [comment]
After some debugging, the crash occurs when compiling a large Logtalk source file. The Logtalk compiler uses three stages. The body of clauses and grammar rules are compiled in the second stage using data collected in the first state. There's no particular term that triggers  the crash, whose details vary (i.e. not always in the `Term.prototype.rename` function) when I do some code instrumentation for debugging. The compilation of the clauses and grammar rule bodies use a Prolog failure loop that can be abstracted as:

```prolog
compile :-
    retract(t(Term)),
    compile(Term, CompiledTerm),
    assertz(c(CompiledTerm)),
    fail.
compile.
```

Is actually far more complex but this should give an idea. Apparently, when the number of `t/1` terms/rules is relatively large (~200 in the file causing the crash), the call stack size is exceeded. The `fail/0` calls trigger backtracking to the `retract/1` call. Wondering if there's any kind of optimization (in Tau Prolog) for this particular pattern that could help here. This is a major roadblock.

**Comment by jariazavalverde** [comment]
A quick test: try reducing the maximum number of resolution steps in the session. This will produce `null` answers, but calling the `answer` method again the process should continue.

**Comment by pmoura** [comment]
Tried several values between 350 to 20000. with the lower values, the message `limit exceeded ;` is repeated multiple times. But the process always ends on the `RangeError` 😔

**Comment by pmoura** [comment]
Found a solution. It turns out that `node` allows setting the maximum stack size at the command-line (I'm using v12.16.3 on macOS):

```bash
$ node --stack_size=5000 ./tp.js 

Logtalk 3.39.0(-)b01
Copyright (c) 1998(-)2020 Paulo Moura

% Default lint compilation flags(:) 
%   unknown_predicates(:) warning(,) undefined_predicates(:) warning
%   unknown_entities(:) warning(,) steadfastness(:) silent(,) naming(:) silent
%   missing_directives(:) warning(,) duplicated_directives(:) warning
%   duplicated_clauses(:) silent(,) portability(:) silent(,) deprecated(:) warning
%   redefined_built_ins(:) silent(,) redefined_operators(:) warning
%   trivial_goal_fails(:) warning(,) always_true_or_false_goals(:) warning
%   lambda_variables(:) warning(,) suspicious_calls(:) warning(,) tail_recursive(:) silent
%   singleton_variables(:) warning(,) underscore_variables(:) singletons
% Default optional features compiler flags(:)
%   complements(:) deny(,) dynamic_declarations(:) deny
%   context_switching_calls(:) allow(,) events(:) deny
% Other default compilation flags(:)
%   report(:) on(,) scratch_directory(:) .(/)lgt_tmp(/)
%   source_data(:) on(,) code_prefix(:) $(,) hook(:) n(/)d
%   optimize(:) off(,) debug(:) off(,) clean(:) on(,) reload(:) changed
% Backend Prolog compiler file compilation and loading flags(:)
%   prolog_compiler(:) []
%   prolog_loader(:)   []
% Read(-)only compilation flags (backend Prolog compiler features)(:)
%   prolog_dialect(:) tau(,) modules(:) supported(,) threads(:) unsupported
%   engines(:) unsupported(,) tabling(:) unsupported(,) coinduction(:) unsupported
%   unicode(:) bmp(,) encoding_directive(:) source
% 
% limit exceeded ;
No settings file found in startup(,) Logtalk user(,) home(,) or config directories.
% Using default flag values set in the backend Prolog compiler adapter file.
% 
% For Logtalk help on libraries(,) entities(,) and built(-)in features(,) use(:)
% (?)(-) {help(loader)}. or (?)(-) logtalk_load(help(loader)).
% 
% For Logtalk compiler warnings(/)errors explanations and fix suggestions(,) use(:)
% (?)(-) {tutor(loader)}. or (?)(-) logtalk_load(tutor(loader)).
% 
```

The output looks a bit funny due to the ()'s around atoms that are defined as operators. This is a Tau Prolog specific issue.

The loading/startup is, however, quite slow due to the compilation of the Logtalk built-in entities (objects and protocols). It can be made much faster by precompiling those entities and modifying the startup process to load the pre-compiled code (by simply changing a flag value).
