### ISSUE TITLE
Output truncated (output buffering bug?)

### ISSUE THREAD

**Issue by pmoura** [tau-prolog/tau-prolog#148]
At Logtalk startup, by default, it prints a banner, the default flag values, information on the settings file being used (if any), and information on how to load the help and tutor tools. The output stops after the default flag values. If I comment out the call (in `core.pl`) that prints the default flag values, then I get all the remaining output. The size of the text from the banner to the default flag values is ~1500 characters. Is there any output buffering limit at play here?

**Comment by pmoura** [comment]
To reproduce the bug, you can use comment out the goal `'$lgt_print_message'(comment(settings), default_flags)` at the end of the `core.pl` file.

The help script that I'm using is:

```js
var readline = require("readline");
var pl = require("./node_modules/tau-prolog/modules/core.js");
require("./node_modules/tau-prolog/modules/format.js")(pl);
require("./node_modules/tau-prolog/modules/js.js")(pl);
require("./node_modules/tau-prolog/modules/lists.js")(pl);
require("./node_modules/tau-prolog/modules/os.js")(pl);
require("./node_modules/tau-prolog/modules/random.js")(pl);
require("./node_modules/tau-prolog/modules/statistics.js")(pl);
//require("./node_modules/tau-prolog/modules/system.js")(pl);

var session = pl.create( 20000 );
var show = x => console.log(pl.format_answer(x, session));
session.consult("../logtalk3/adapters/unsupported/tau.pl", {success: function() {
    session.consult("../logtalk3/paths/paths.pl", {success: function() {
        session.consult("../logtalk3/core/core.pl", {success: function() {
//            session.query("write(done), nl.");
//            session.answers(show);
        }, error: show});
    }, error: show});
}, error: show});

var max_answers = process.argv[2] || 100;
var rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: false
});

rl.on('line', function(query) {
    if(query.length > 0) {
        var parsed = session.query(query);
        if(parsed === true)
            session.answers(x => console.log("\n" + pl.format_answer(x, session)), max_answers);
        else
            console.log(pl.format_answer(parsed, session));
    }
});
```

The script is called using:

```bash
$ node --stack_size=10000 ./taulgt.js
```

Beware that startup is quite slow. To speed it up, change in `core.pl` around line 26679 the option `clean(on)` to `clean(off)`. This will make startups after the first one much faster.

**Comment by pmoura** [comment]
@jariazavalverde verified that this problem doesn't occur on Linux. I am on macOS.

**Comment by pmoura** [comment]
Your a31ca8e5e6f6a44e5224a6e3277a90c20d85cfc7 commit solved the truncated output for me on macOS.

**Comment by jariazavalverde** [comment]
I guess the parser wasn't finishing parsing the entire file due to excessive recursion. I had a similar problem on Windows, where execution ended after parsing ~ 21000 lines.
