### ISSUE TITLE
op/3 goal activates operator but fails immediately after

### ISSUE THREAD

**Issue by pmoura** [tau-prolog/tau-prolog#156]
Found a case where `read_term/3` fails to parse a valid term:

```prolog
:- public(op(700, xfx, ('=~='))).
```

The term is found in the `logtalk3/library/types/number.lgt`. If I comment out that line (52), I get, as expected:

```text
?- {types(number)}.
(*)     Reference to unknown object(:) atomic
*       while compiling object number
*       in file (/)Users(/)pmoura(/)logtalk(/)library(/)types(/)number.lgt at or above line (-)1
*     
% [ (/)Users(/)pmoura(/)logtalk(/)library(/)types(/)number.lgt loaded ]
% 1 compilation warning
true ;
false.
```

But with the pristine file (after restarting the process), the compilation fails:

```text
?- {types(number)}.
false.
```

The odd thing is that the same `read_term/3` goal in isolation works:

```text
?- current_input(Stream), read_term(Stream, Term, [variable_names(Variables)]).
:- public(op(700, xfx, ('=~='))).
Stream = <stream>(3), Term = (:-public(op(700, xfx, (=~=)))), Variables = [].
false.
```

**Comment by pmoura** [comment]
After more detailed debugging, this is actually a bug wen calling the `op/3` predicate. The Logtalk compiler parsing of the `:- public(op(700, xfx, ('=~='))).` term results eventually in the call `op(700, xfx, ('=~=')`. The operator is set but the `op/3` fails immediately after.

**Comment by pmoura** [comment]
To reproduce the bug, try:

```text
?- op(700, xfx, foo).
false.
?- current_op(700, xfx, foo).
true ;
false.
```

**Comment by jariazavalverde** [comment]
> After more detailed debugging, this is actually a bug wen calling the `op/3` predicate. The Logtalk compiler parsing of the `:- public(op(700, xfx, ('=~='))).` term results eventually in the call `op(700, xfx, ('=~=')`. The operator is set but the `op/3` fails immediately after.

Thank you! You saved me a lot of time.

**Comment by pmoura** [comment]
Just checked the fix. Problem solved. Thanks for the quick reply. Sorry for the initial misleading description of the problem.
