### ISSUE TITLE
Predicate for accessing the operating system current date and time

### ISSUE THREAD

**Issue by pmoura** [tau-prolog/tau-prolog#160]
Please consider adding to `library(os)` a predicate to convert the `get_time/1` value into the current date and time or a predicate to directly return the current date (year, month, and day) and time (hours, minutes, seconds, possibly also mili-seconds).

**Comment by jariazavalverde** [comment]
Added `time_property/2` (`time_property(+Time, ?Property)`) built-in predicate. Properties:

- `year/1`: Get the year as a four digit number (yyyy).
- `month/1`: Get the month as a number (0-11).
- `day/1`: Get the day as a number (1-31).
- `hours/1`: Get the hour (0-23).
- `minutes/1`: Get the minute (0-59).
- `seconds/1`: Get the second (0-59).
- `milliseconds/1`: Get the millisecond (0-999).
- `weekday/1`: Get the weekday as a number (0-6).

**Comment by pmoura** [comment]
Thanks!
