### ISSUE TITLE
Severe performance degradation

### ISSUE THREAD

**Issue by pmoura** [tau-prolog/tau-prolog#196]
Something in recent bug fixes is causing a quite severe performance degradation. When using Logtalk for testing, first time compilation of the "lgtunit" tool (following the procedure described in the `TESTING.md` file) that used to take minutes now takes several hours. Possibly the performance degradation is caused by some new code, maybe some processing loop, that doesn't scale when compiling sizable source files.

**Comment by jariazavalverde** [comment]
Please let me know if 7a1b35c fixes the problem. I am running the tests to debug the issue #164, and finally after these changes I managed to execute them.

**Comment by pmoura** [comment]
Testing the fix...

**Comment by pmoura** [comment]
... much faster now. Not clear however is the fix accounts for all causes of the performance degradation. I cannot directly compare times as I'm running the current Logtalk git version that takes advantage of the recently added stream position support and also performs a few more lint checks (which expose a Tau Prolog bug that so far I have been unable to isolate; that bug causes most of the unexpected warnings with the `{lgtunit(loader)}` goal).

**Comment by pmoura** [comment]
Regarding testing, please see if you can help with https://github.com/LogtalkDotOrg/logtalk3/issues/80 This would allow us to automate testing. Also note that the current Logtalk git version includes updates for Tau Prolog (but you're using it already, I expect?).

**Comment by jariazavalverde** [comment]
> Also note that the current Logtalk git version includes updates for Tau Prolog (but you're using it already, I expect?).

Yes, I'll run the rest of the tests this week and over the weekend I'll try to update all the documentation to release version 0.3.0.
