### ISSUE TITLE
Question: Recursion in Tau-Prolog

### ISSUE THREAD

**Issue by d4hines** [tau-prolog/tau-prolog#210]
Hi!

I'm having trouble with recursive rules in Tau prolog. I'm sure it's a simple matter, but I've only worked with declarative systems like Datalog and ASP so I've never run into this problem before.

Here's an example:
```
n(3).
time(N) :- n(N).
time(Y) :- time(X), X > 0, Y is X -1.
```

When I run this query:
```
?- time(X).
```
the program produces the correct answers (X = 3,2,1,0), and then it goes into an infinite loop, either crashing the browser or giving "limit exceeded ;". What am I doing wrong here? I have the same problem for the transitive closure:

```
ancestor(A, B) :- parent(A, B).
ancestor(A, B) :- ancestor(A, C), parent(C, B).
```

Any help would be greatly appreciated.
Thanks.

**Comment by pmoura** [comment]
Prolog cannot handle left-recursion without tabling support. Write instead:

```prolog
ancestor(A, B) :- parent(A, B).
ancestor(A, B) :- parent(A, C), ancestor(C, B).
```
