### ISSUE TITLE
Strange "existence_error/2"

### ISSUE THREAD

**Issue by d4hines** [tau-prolog/tau-prolog#213]
Hello,

I'm hitting a weird error in nodejs. I have the following program: http://www.tau-prolog.org/sandbox/dCLYntSo 

I'd like to run this query:
```
holds(visible(Todo), true, 0).
```
expecting the answers `Todo = 1..3`.

On the sandbox, this is exactly what I get. 

However, in my NodeJS tests,
I get this error (console.logged):
```javascript
console.log(answer.args[0].args[0])
/* =>
Term {
  ref: 111808,
  id: 'existence_error',
  args: [
    Term {
      ref: 111807,
      id: 'procedure',
      args: [],
      indicator: 'procedure/0'
    },
    Term { ref: 111806, id: '/', args: [Array], indicator: '//2' }
  ],
  indicator: 'existence_error/2'
}*/
```

How can I get past this issue?

I noticed two things:
- The version on the sandbox is 0.2.87, but the latest on NPM is 0.2.81. It would be great if that were the issue.
- This existence error looks similar to the one i get when I run the query without consulting the program in the sandbox. Is that a clue?

Thanks

**Comment by d4hines** [comment]
I just tried using a local import of the latest version of core.js (from HEAD of master branch), and I'm still getting the same error, so I don't think it's a versioning issue.

**Comment by d4hines** [comment]
Ah, I think I've figured it out: I'm using the list module, but it's not included.

**Comment by jariazavalverde** [comment]
> Ah, I think I've figured it out: I'm using the list module, but it's not included.

You must import the `lists` module in node:

```js
var pl = require("./path/to/tau-prolog.js");
require("./path/to/tau-prolog/lists.js")( pl );
```

and load it in your Prolog program:

```prolog
:- use_module(library(lists)).
```
