### ISSUE TITLE
RELEASE_NOTES: charsio module provides reasoning about lists of characters

### ISSUE THREAD

**Issue by triska** [tau-prolog/tau-prolog#216]
Congratulations on 0.3.0!

The [RELEASE_NOTES](https://github.com/tau-prolog/tau-prolog/blob/v0.3.0/RELEASE_NOTES.md#version-030---august-31-2020) mention:

<blockquote>
ADDED: <tt>charsio</tt> module for I/O on lists of character codes.
</blockquote>

which should rather read: "... on lists of **characters**."

It is extremely encouraging to see strong built-in support for reasoning about lists of characters in Tau Prolog!

**Comment by jariazavalverde** [comment]
Fixed. Thank you!

The `charsio` library is still incomplete, as it only has the required predicates for your `format` module. The rest of predicates will be added in the next version.

**Comment by triska** [comment]
Thank you a lot!

Regarding `charsio`: I think a good strategic direction for Prolog systems would be to encourage describing output declaratively with DCGs (using for instance `format_//2` from `library(format)`), and then to provide `phrase_to_file/2` so that the described output can be efficiently written to a file when needed. Currently, no system provides `phrase_to_file/2` yet, so this is an area where Tau&nbsp;Prolog could truly pave the way for better, more declarative language constructs. The construct is used as `phrase_to_file(NT, File)`, and writes the list of characters described by the nonterminal&nbsp;`NT` to&nbsp;`File` as they become known.
