### ISSUE TITLE
Compatibility request variable_names/1 write option

### ISSUE THREAD

**Issue by jburse** [tau-prolog/tau-prolog#221]
This is part of Corrigendum Nr. 3 of the ISO core standard
seems to be missing from the TauProlog implementation:

**7.10.4 Write-options list**
variable_names(VN_list)
[https://www.complang.tuwien.ac.at/ulrich/iso-prolog/WDCor3](https://www.complang.tuwien.ac.at/ulrich/iso-prolog/WDCor3)

I wanted to run Joseph Vidal-Rosset quine in the TauProlog sandbox.
The read_term/2 did work, a little dialog appeared, and I could
enter A=>(B=>A) as an example. But then I got caught by this:
```
?- quine.
uncaught exception: error(domain_error(write_option,variable_names(['A'=_114,'B'=_89])),write_term/3)
```

The source code that I pasted into the sandbox consult area:

**Vidals Code from SWI-Prolog Discourse**
[https://\github.com/jburse/ethz-proquel/blob/master/misc_others/vidal/quine.pl](https://github.com/jburse/ethz-proquel/blob/master/misc_others/vidal/quine.pl)

**Comment by jburse** [comment]
This would be a tricky test case, verifying the specification
in ISO core standard Corrigendum 3 7.10.4 Write-options list:

?- A = Roger, write_term(foo(A+Roger,A+H),[variable_names(['A'=A,'Roger'=Roger,'_'=H])]), nl.
foo(A+A,A+_)

**Comment by jariazavalverde** [comment]
Added! Thanks for the report.

![variable_names](https://user-images.githubusercontent.com/5055295/111919747-d8f5b280-8a8b-11eb-966c-b6e0b2fd7f8d.png)
