### ISSUE TITLE
JS function value handling error

### ISSUE THREAD

**Issue by totpet** [tau-prolog/tau-prolog#224]
Hi!

I was experimenting with calling JS functions in the sandbox, and I think I found a bug in the handling of some JS values.

I simply load the `js` module:
```Prolog
:- use_module(library(lists)).
:- use_module(library(js)).
```

Then get the global `alert` function, and try calling and examining it: 
```Prolog
prop(alert, A), write(A), nl, apply(A, [test],Y), A =.. AL.
```

The call works, I get the alert window, but `write` outputs `<javascript>(function)`, which is parsed as HTML and only "`(function)`" is visible.

Then I tried to examine the value of `A`, the call to the decomposition operator causes this error:

```
javascript error: TypeError: atom.args[0].args is undefined
```

Further queries after this are parsed successfuly, but no result is displayed, e.g.:
![image](https://user-images.githubusercontent.com/13013768/94589021-06a03280-0285-11eb-9e96-cb3541475700.png)
Instead of:
![image](https://user-images.githubusercontent.com/13013768/94589079-1b7cc600-0285-11eb-89e2-428f6988963b.png)

----

My guess is that this has to do with the   [implementation of the `=..` operator](https://github.com/tau-prolog/tau-prolog/blob/f6fd48b9ba393afdf3c3c195b1affd72a7a32f34/modules/core.js#L5907)

Or maybe [`pl.type.JSValue.prototype.toString`](https://github.com/tau-prolog/tau-prolog/blob/f6fd48b9ba393afdf3c3c195b1affd72a7a32f34/modules/js.js#L405) or `unify`

**Comment by jariazavalverde** [comment]
Thank you very much for your report. Indeed, it was an error in the **(=..)/2** built-in predicate when called with terms other than atoms or numbers. The fix will be available in the next release.
