### ISSUE TITLE
Erratic behaviour of unify_with_occurs_check/2 for cyclic terms

### ISSUE THREAD

**Issue by jburse** [tau-prolog/tau-prolog#235]
Its somehow not clear what the semantics is of unify_with_occurs_check/2 
for cyclic terms. On one hand I get:
```
?- X = s(X), unify_with_occurs_check(Z-Z, s(Z)-X).
false.
?- X = s(X), unify_with_occurs_check(Z-Z, X-s(Z)).
false.
```
On the other hand I get:
```
?- X = f(X), unify_with_occurs_check(X, X).
X = f(X).
```

**Comment by jariazavalverde** [comment]
I see similar behavior in SWI-Prolog and GNU Prolog.

**Comment by jburse** [comment]
SWI-Prolog is worse:
```
/* SWI-Prolog (threaded, 64 bits, version 8.3.20) */

?- X = s(X), unify_with_occurs_check(Z-Z, s(Z)-X).
false.

?- X = s(X), unify_with_occurs_check(Z-Z, X-s(Z)).
X = Z, Z = s(Z).
```
But maybe corner case of cyclic term input to unify_with_occurs_check/2 
can be anyway ignored. So closing this ticket.
