### ISSUE TITLE
Error in the Javascript code from the Tutorial

### ISSUE THREAD

**Issue by erikkaplun** [tau-prolog/tau-prolog#238]
<img width="713" alt="image" src="https://user-images.githubusercontent.com/17533/106294800-489fac00-6258-11eb-8f30-db7474a5bea1.png">

Also tried to load `code.pl` from a URL (both relative and absolute), to no avail.  Has the Javascript API changed since the writing of the tutorial?

**Comment by jariazavalverde** [comment]
Yes, version 0.3.0 introduced a backward-incompatible change to the `query` and `consult` methods. You can see the [RELEASE NOTES](https://github.com/tau-prolog/tau-prolog/blob/master/RELEASE_NOTES.md#version-030---august-31-2020).

The tutorial has been updated according to the new API:

- https://github.com/tau-prolog/manual/blob/master/en/a-simple-tutorial.md
- http://tau-prolog.org/manual/a-simple-tutorial

Although there are still some pages to update. What tutorial did you read?

**Comment by erikkaplun** [comment]
Oops, the tutorial I was referring to was not even on TauProlog's web site. My bad. (it was this one, for the record: https://pbrown.me/blog/hello-tau-prolog/) Sorry for the false alert and thank you for the reply!

**Comment by jariazavalverde** [comment]
No problem! Thanks for the notice anyway.
