### ISSUE TITLE
Feature request \uXXXX escape sequence

### ISSUE THREAD

**Issue by jburse** [tau-prolog/tau-prolog#240]
It could be a new trend of using more Unicode in Prolog.
JCR does also something with Unicode here [Logic Programming 
for Theory Representation and Scientific Inference in Psychology](https://www.sciencedirect.com/science/article/pii/S0732118X20302130?via%3Dihub) .

Out of habituation I tried this in TauProlog, but it didn't work:
```
?- X = '\u2200'.
error parsing query: throw(error(syntax_error('unexpected token'),
[line(1),column(4),found('unknown escape sequence')]))
```
On the other hand SWI-Prolog can do it:
```
?- X = '\u2200'.
X = ∀ .
```
The \\uXXXX escape sequence is not found in the ISO core standard,
but a couple of Prolog systems started supporting it, lilke SWI-Prolog,
Jekejeke Prolog, etc.. How about supporting it as well?

**Comment by jariazavalverde** [comment]
Added. It is just a particular case of the **\x\\** escape sequence.

![unicode](https://user-images.githubusercontent.com/5055295/112004529-2cb2db00-8b22-11eb-9991-0231dc1b6cf7.png)
