### ISSUE TITLE
Unexpected behavior with predicate_property/2

### ISSUE THREAD

**Issue by JeanChristopheRohner** [tau-prolog/tau-prolog#242]
In the Sandbox, with the lists module loaded, it get `false` with the goal `predicate_property(member(_, _), P).`.

Shouldn't this yield `P = static`?

**Comment by jariazavalverde** [comment]
Sorry for the delayed response.
In Tau, when the predicates belong to modules other than the `user` module, it is necessary to make it explicit. 

```prolog
?- predicate_property(lists:member(_,_), P).
P = static.
```

**Comment by JeanChristopheRohner** [comment]
No problem with the delay! And thanks again for making Tau Prolog :-)
