### ISSUE TITLE
Consulting in node doesn't seem to work (getting existence_errors)

### ISSUE THREAD

**Issue by atava** [tau-prolog/tau-prolog#245]
This must be a very silly thing and sorry for opening an issue about it, but I've not been able to find a solution for quite some time now.

I'm just trying to test tau-prolog in node.
Any program I try (it doesn't matter what predicates I put in it) doesn't seem to be read at all. I get existence_errors when querying for any custom predicates.
The engine works, though, because if I try core predicates such as `X is 2 + 3` I can get answers.
In the examples I'm using ES modules but that shouldn't matter (if I switch to CS modules I get the same problem).

Here's the code:
    
    import pl from 'tau-prolog';
    const session = pl.create();
    
    session.consult(`
        parent(tom, jack).
    
        male(tom).
    
        father(A, B) :-
            male(A), parent(A, B).
        `);
    
    session.query('father(A, B).');
    
    session.answers(x => console.log(pl.format_answer(x)));

Node version is 14.16.1 and tau-prolog 0.3.0.

**Comment by jariazavalverde** [comment]
Please, check the changes to the `consult` and `query` methods in version 0.3.0:

https://github.com/tau-prolog/tau-prolog/blob/master/RELEASE_NOTES.md#version-030---august-31-2020

**Comment by atava** [comment]
Hi, thank you. It now works.
I appreciate this library and will test it thoroughly (I come from SWI-Prolog).

Is there any plan to add a Promise-based asynchronous pattern in addition to callbacks?

**Comment by jariazavalverde** [comment]
There is an open pull request to add promises (https://github.com/tau-prolog/tau-prolog/pull/236). I don't know exactly when, but possibly I'll add the promise interface via a package to keep the core as is.

**Comment by atava** [comment]
Good to know. Thanks.
