### ISSUE TITLE
Ad-hoc modules or DCG and modules do not work

### ISSUE THREAD

**Issue by ghost** [tau-prolog/tau-prolog#258]
Was trying this Prolog text. It did consult:
```
foo:bar --> jack:jill.
```
But then I am not sure whether the result is correct, I am expecting a different head:
```
listing.
% :/4
:(foo,bar,_1,_2) :- jack:jill(_1,_2).
```
Obviously it doesn't run:
```
?- foo:bar(1,2).
uncaught exception: error(existence_error(procedure,bar/2),top_level/0)
```

**Comment by jariazavalverde** [comment]
Fixed. Thanks for your report.

![imagen](https://user-images.githubusercontent.com/5055295/152522242-fce0258b-f5ab-4ce0-b951-f47e6195b10f.png)
