### ISSUE TITLE
DCGs with a variable as a subgoal cause an internal error

### ISSUE THREAD

**Issue by mb64** [tau-prolog/tau-prolog#263]
I tried the code:
```prolog
f(F) --> F.
```

This makes Tau Prolog give an internal type error, [on this line](https://github.com/tau-prolog/tau-prolog/blob/master/modules/core.js#L1437), since `expr` represents the subgoal `F` which doesn't have an `args` field.

**Comment by jariazavalverde** [comment]
Fixed. Thanks for your report.

![imagen](https://user-images.githubusercontent.com/5055295/152523119-005cb8bf-9f51-4380-8361-6ed1d45f0863.png)
