### ISSUE TITLE
format/2-3 predicates missing the numbervars(true) option in the ~w and ~q formats

### ISSUE THREAD

**Issue by pmoura** [tau-prolog/tau-prolog#275]
Please see https://github.com/mthom/scryer-prolog/pull/1082 The fix is simple and the same for Tau Prolog. But I only find in the sources the compiled form of the `format.pl` library.

**Comment by jariazavalverde** [comment]
I was trying to port the latest version from Scryer, but I can't find information about the `unique_variable_names/2` predicate. @triska

**Comment by jariazavalverde** [comment]
Updated.

(The source code is now in [/lib/format.pl](https://github.com/tau-prolog/tau-prolog/blob/master/lib/format.pl)).
