### ISSUE TITLE
atom_concat/3 throws type_error/2 when you pass in two different primitives

### ISSUE THREAD

**Issue by emummel20** [tau-prolog/tau-prolog#277]
In swipl, this works

```
?- atom_concat('hello',42,Foo).
Foo = hello42.
```

in Tau, it's giving me type_error/2. Just wanted to let you know in case this was not a known issue.

**Comment by pmoura** [comment]
Unlike in SWI-Prolog, the implementation of the `atom_concat/3` predicate in Tau Prolog is ISO Prolog Core standard compliant. Thus, a type error for that query is the correct and expected result. To concatenate two *atomic* terms, use instead the `atomic_concat/3` built-in predicate.

**Comment by emummel20** [comment]
atomic_list_concat/2/3? Thanks, I do see `atomic_list_concat(['hello',43],Concat).` works.

**Comment by pmoura** [comment]
Tau Prolog provides both `atomic_concat/3` and `atomic_list_concat/2-3` built-in predicates. If you have only two atomic terms to concatenate, `atomic_concat/3` is more efficient.

**Comment by emummel20** [comment]
oh ok sorry, I checked and didn't see atomic_concat/3 documented on the site so I thought it was a typo. In that case, I am getting an `existence_error/2` for `atomic_concat('hello',43,Foo).` right now. Is that how you run it?

**Comment by pmoura** [comment]
You need the latest Tau Prolog git version to use it. It was added after the 0.3.1 release.

**Comment by emummel20** [comment]
Ah, got it. I'm currently on 3.1. Alright, thank you very much for the speedy response! Please keep up the great work. This project is fantastic.

**Comment by pmoura** [comment]
@jariazavalverde Maybe tag 0.3.2?

**Comment by jariazavalverde** [comment]
Thanks for the help @pmoura! In fact, it's time to update.
