### ISSUE TITLE
Limit exceeded

### ISSUE THREAD

**Issue by triska** [tau-prolog/tau-prolog#278]
When I enter the program below in the sandbox, and then post `?- g.` as the query, I get:

<pre>
<b>?- g.</b>
limit exceeded ;
parsing query: g ok!
?- consult
parsing program: ok!
</pre>

Could you please have a look and let me know how I can solve this issue? Thank you a lot!

<pre>
:- use_module(library(lists)).
:- use_module(library(format)).

:- op(500, yfx, xor).

g :-
        findall(K, between(1,32,K), Key),
        salsa20_init(Key, [3,1,4,1,5,9,2,6], [7,0,0,0,0,0,0,0], As0),
        salsa20(As0, As),
        format("~n~nResult:~n~n", []),
        hex_array(As).

quarter_round(1, [A,B,C,D,
                  E,F,G,H,
                  I,J,K,L,
                  M,N,O,P],
              [A,B,C,D xor rotl(P+L,7),
               E xor rotl(A+M,7),F,G,H,
               I,J xor rotl(F+B,7),K,L,
               M,N,O xor rotl(K+G,7),P]).
quarter_round(2, [A,B,C,D,
                  E,F,G,H,
                  I,J,K,L,
                  M,N,O,P],
              [A,B,C xor rotl(K+O,9),D,
               E,F,G,H xor rotl(P+D,9),
               I xor rotl(A+E,9),J,K,L,
               M,N xor rotl(F+J,9),O,P]).
quarter_round(3, [A,B,C,D,
                  E,F,G,H,
                  I,J,K,L,
                  M,N,O,P],
              [A,B xor rotl(J+N,13),C,D,
               E,F,G xor rotl(O+C,13),H,
               I,J,K,L xor rotl(D+H,13),
               M xor rotl(E+I,13),N,O,P]).
quarter_round(4, [A,B,C,D,
                  E,F,G,H,
                  I,J,K,L,
                  M,N,O,P],
              [A xor rotl(I+M,18),B,C,D,
               E,F xor rotl(B+N,18),G,H,
               I,J,K xor rotl(C+G,18),L,
               M,N,O,P xor rotl(H+L,18)]).

apply_quarter_round(N, As0, As) :-
        quarter_round(N, As0, Rules),
        maplist(eval_, Rules, As),
        format("~nquarter round ~d:~n", [N]),
        hex_array(As).

eval_([B|Bs], [B|Bs]).          % unchanged binary string
eval_(X xor rotl(A+B,R), Bs) :-
        plus_(A, B, Ss),
        rotl_(Ss, R, Rs),
        maplist(xor_, X, Rs, Bs).

xor_('0', '0', '0').
xor_('0', '1', '1').
xor_('1', '0', '1').
xor_('1', '1', '0').

/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
?- integer_word(5, Ws) ; false.
%@    Ws = "0000000000000000000 ..."
%@    Ws = "00000000000000000000000000000101"
%@ ;  false.

?- integer_word(5, Ws), rotl_(Ws, 1, Rs) ; false.

00010

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */

rotl_(Bs0, R, Bs) :-
        length(Ls, R),
        append(Ls, Rs, Bs0),
        append(Rs, Ls, Bs).

plus_(As, Bs, Ss) :-
        binary_decimal(As, DA),
        binary_decimal(Bs, BA),
        S is (DA + BA) mod 2^32,
        integer_word(S, Ss).

salsa20(As0, As) :-
        format("starting: ~n~n", []),
        hex_array(As0),
        findall(N, between(1,20,N), Rounds),
        foldl(apply_round, Rounds, As0, As1),
        maplist(plus_, As0, As1, As).

apply_round(R, As0, Ts) :-
        format("~n~nRound ~d~n~`=t~20+~n", [R]),
        foldl(apply_quarter_round, [1,2,3,4], As0, As),
        As = [A,B,C,D,
              E,F,G,H,
              I,J,K,L,
              M,N,O,P],
        Ts = [A,E,I,M,
              B,F,J,N,
              C,G,K,O,
              D,H,L,P].

hex_array(As) :-
        phrase(hex_array(As), Ls),
        format("~s", [Ls]).

hex_array(As) -->
        { maplist(word_hex, As, Hs) },
        hex_lines(Hs).

hex_lines([]) --> [].
hex_lines([A,B,C,D|Ls]) -->
        format_("~s   ~s   ~s   ~s~n", [A,B,C,D]),
        hex_lines(Ls).

salsa20_init(Key, Nonce, Counter, As) :-
        As = [A,B,C,D,
              E,F,G,H,
              I,J,K,L,
              M,N,O,P],
        integer_word(0x61707865, A),
        length(KeyLeft, 16),
        append(KeyLeft, KeyRight, Key),
        bytes_words(KeyLeft, [B,C,D,E]),
        integer_word(0x3320646e, F),
        bytes_words(Nonce, [G,H]),
        bytes_words(Counter, [I,J]),
        integer_word(0x79622d32, K),
        bytes_words(KeyRight, [L,M,N,O]),
        integer_word(0x6b206574, P).

integer_word(C, W) :-
        phrase(format_("~`0t~2r~32+", [C]), W).

bytes_words([], []).
bytes_words([A,B,C,D|Bs], [W|Ws]) :-
        phrase(bytes([D,C,B,A]), W),
        bytes_words(Bs, Ws).

bytes([]) --> [].
bytes([B|Bs]) -->
        format_("~`0t~2r~8+", [B]),
        bytes(Bs).

binary_decimal(Bs, D) :-
        maplist(b_i, Bs, Is),
        foldl(plus_times2, Is, 0, D).

plus_times2(I, S0, S) :- S is 2*S0 + I.

b_i('0', 0).
b_i('1', 1).

word_hex(Bytes, Hex) :-
        binary_decimal(Bytes, D),
        phrase(("0x",format_("~`0t~16r~8+", [D])), Hex).
</pre>

**Comment by jariazavalverde** [comment]
It seems to be working properly. Tau Prolog sets a limit of resolution steps so that the browser does not freeze. If you press enter again, the search continues.

![Screenshot 2021-12-15 at 15-11-21 Tau Prolog Sandbox](https://user-images.githubusercontent.com/5055295/146202573-2285c17d-b223-4d72-83ea-321004532bd9.png)

**Comment by triska** [comment]
Thank you! I have tried it with Firefox, setting the limit to `100000000`, and I only get repeated `limit exceeded` messages:

<pre>
limit exceeded ;
limit exceeded ;
limit exceeded ;
limit exceeded ;
limit exceeded ;
parsing query: g ok!
</pre>

I would like to run the query for as long as it needs, I have filed #279 to propose adding an option that removes the limit entirely.

**Comment by jariazavalverde** [comment]
I close this issue to continue the discussion at https://github.com/tau-prolog/tau-prolog/issues/281.
