### ISSUE TITLE
"Unlimited" option would be useful

### ISSUE THREAD

**Issue by triska** [tau-prolog/tau-prolog#279]
In tasks such as #278, I would like to be able to run the Prolog process for *as long as is needed* to obtain the result. For this, it would be useful to have an "Unlimited" option, which could for example be a *check&nbsp;box* that hides the input&nbsp;field for the limit entirely, and ignores any specified limit.

Would you please consider adding such a feature to Tau&nbsp;Prolog? Thank you a lot!

**Comment by jariazavalverde** [comment]
You can set the limit to `0` for that (you must reconsult after setting the limit in the sandbox).

**Comment by jariazavalverde** [comment]
I close this issue to continue the discussion at https://github.com/tau-prolog/tau-prolog/issues/281.
