### ISSUE TITLE
Example how to process answers with lists in JavaScript 

### ISSUE THREAD

**Issue by carstenheisterkamp** [tau-prolog/tau-prolog#280]
Please add an example of how to process lists in JavaScript.
How do I access the list in an answer from JavaScript?

I have a simple program and goal which returns a list in its answer.
` test(t, [64,65,100,120]).`

Goal: 
`test(t, X).`

`console.log(session.format_answer(answer));
X = [64,65,100,120]`

I would like to convert the list in the answer into an JS array. 
When I try

`answer.lookup("X")` 
it returns the term

I figured out to get single list elements recursively, e.g.
console.log(answer.links.X.args[1].args[1].args);

But how to get the whole list at once `[64,65,100,120]` which would be great to iterate over it in JS.

**Comment by jariazavalverde** [comment]
You can write a function to transform Prolog lists to arrays:

```js
function fromList(xs) {
    var arr = [];
    while(pl.type.is_term(xs) && xs.indicator === "./2") {
        arr.push(xs.args[0]);
        xs = xs.args[1];
    }
    if(pl.type.is_term(xs) && xs.indicator === "[]/0")
        return arr;
    return null;
}
```
Example:
```js
var session = pl.create();
session.query("X = [1,2,3].");
session.answer(a => console.log(fromList(a.lookup("X")))); // [ {...}, {...}, {...} ]
```

If the list only contains ground terms, you can directly use the `toJavaScript` method:
```js
var session = pl.create();
session.query("X = [1,2,3].");
session.answer(a => console.log(a.lookup("X").toJavaScript())); // [ 1, 2, 3 ]
```

Anyway, I recommend the first option.

**Comment by carstenheisterkamp** [comment]
Both options work like a charm, many thanks for your quick reply.
