### ISSUE TITLE
parse(unparse(T)) != T

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [tau-prolog/tau-prolog#282]
Just playing around with the Tau Prolog sandbox version 0.3.1 (beta). 
Somehow here something goes wrong:
```
unparse(^(-(a),b)) = '- a^b'.
parse('- a^b') = -(^(a,b)) != ^(-(a),b))
```
![Unbenannt](https://user-images.githubusercontent.com/95891213/150607217-39b51d8e-cc1e-4923-aedc-2ac7d2fc30b3.PNG)

**Comment by Jean-Luc-Picard-2021** [comment]
From GNU Prolog, I guess unparse should give '(- a)^b':

![image](https://user-images.githubusercontent.com/95891213/150608310-65b87e9a-93b0-4261-979e-44291df7a03f.png)

**Comment by jariazavalverde** [comment]
It seems like a problem with the `(-)/1` operator when printing the term.

I'll check it. Thanks.
