### ISSUE TITLE
Unexpected result with findall/3

### ISSUE THREAD

**Issue by josd** [tau-prolog/tau-prolog#285]
For the following program in http://tau-prolog.org/sandbox/
```
test :-
    findall([A,_],p(A,_),L),
    write(L),
    nl.

p(a,b).
p(c,d).
p(e,f).
```
the query
```
test.
```
gives
```
[[a,__2],[c,__2],[e,__2]]
```
whereas the expectation is somtehing like
```
[[a,_2],[c,_3],[e,_4]]
```

**Comment by pmoura** [comment]
@jariazavalverde Looking at the fix, the bug is only on the top-level printing of query bindings, correct?

**Comment by jariazavalverde** [comment]
> the bug is only on the top-level printing of query bindings

@pmoura I'm not sure I'm getting this right. It wasn't just a printing problem: if a variable was subsequently instantiated, all of them were instantiated. 

Before:
![imagen](https://user-images.githubusercontent.com/5055295/152782242-be0f197a-dd7f-461a-933a-b91ef409aab5.png)

Now:
![imagen](https://user-images.githubusercontent.com/5055295/152783029-f0b659a7-8956-4ff0-86ac-1b0e1f13a252.png)

**Comment by pmoura** [comment]
I have not yet update my local installation with the fix. I get:

```text
?- assertz(f(_, 1)).
true.

?- assertz(f(_, 2)).  
true.

?- findall(Var, f(Var, _), [X, Y]), X \== Y.
true.

?- findall((A1,A2), f(A1,A2), [(B1,1),(B2,2)]), B1 \== B2.
true.
```

I'm trying to define one or more additional Logtalk tests for the `findall/3` predicate based on @josd finding and example code.

**Comment by josd** [comment]
In https://github.com/IDLabResearch/Webeye/blob/master/examples/fourcolor.pl#L6
originally had `findall([Place,_],'https://idlabresearch.github.io/ns#neighbours'(Place,_),Places),`
and that now works fine!

**Comment by jariazavalverde** [comment]
@pmoura Try with a variable not in the goal. You should get something like:

```prolog
?- assertz(f(1)).
true.

?- assertz(f(2)).  
true.

?- findall((B,A), f(A), [(B1,1),(B2,2)]), B1 \== B2.
false.
```

**Comment by pmoura** [comment]
That clarifies it, thanks. Test added (https://github.com/LogtalkDotOrg/logtalk3/commit/72f5836dc190ccae4a4280c5085ac8981132aa3f).

**Comment by josd** [comment]
Couldn't reopen this issue but it is again occuring in 0.3.3
![image](https://user-images.githubusercontent.com/193444/170862509-27e0bfe1-2b16-4c97-86bd-71a7abb39185.png)

**Comment by jariazavalverde** [comment]
Fixed again. Thanks.

**Comment by josd** [comment]
Thanks a lot and now we get the correct results in https://github.com/josd/eyebrow/commit/95946ec831fa8d960900cc73d611c6c89bf12ee0

**Comment by pmoura** [comment]
Tests exist that can prevent these regressions... running them before a new release would be a good idea. The whole testing process can also be automated using a GitHub workflow. A good example is https://github.com/trealla-prolog/trealla/blob/main/.github/workflows/compliance.yml
