### ISSUE TITLE
walltime undocumented

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [tau-prolog/tau-prolog#289]
As a [workaround](https://github.com/tau-prolog/tau-prolog/issues/288) for time/1 in browser, I tried:
```
time2(G,T) :- 
   statistics(walltime, T1), 
   G, 
   statistics(walltime, T2), 
   T is T2-T1.
```
But walltime isn't documented here:

[http://tau-prolog.org/documentation/prolog/statistics/statistics/2](http://tau-prolog.org/documentation/prolog/statistics/statistics/2)

So I am not 100% sure what it returns.

**Comment by pmoura** [comment]
The `walltime` statistics was introduced at https://github.com/tau-prolog/tau-prolog/pull/217 It returns `Date.now()` as you can see in the code changes. Hope this helps.

**Comment by Jean-Luc-Picard-2021** [comment]
Maybe next time when you do code changes, also update the docu.
Also this here is a little meager:
