### ISSUE TITLE
Uncatalogued sleep/1

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [tau-prolog/tau-prolog#292]
I do not find sleep/1 here in the library(os) inventory listed:

http://tau-prolog.org/documentation#os

but a little URL engineering gives me:

http://tau-prolog.org/documentation/prolog/os/sleep/1

**Comment by Jean-Luc-Picard-2021** [comment]
Maybe its uncatalogued because it doesn't work?

Can sleep/1 reliably be used in negation as failure? 

I am asking because the JavaScript returns true.

**Comment by Jean-Luc-Picard-2021** [comment]
Maybe its uncatalogued because it doesn't work?
Can sleep/1 reliably be used in negation as failure?
I am asking because the JavaScript returns true.

Ok so testing shows there is possibly no problem:
```
:- use_module(library(os)).
foo :- sleep(0).
bar :- fail.
baz :- \+ (foo, bar).

?- baz.
true.
```
Seems I am not used to the FFI protocol of Tau Prolog.

**Comment by jariazavalverde** [comment]
It is not listed because it previously belonged to a module that no longer exists. The predicate works fine, but you have to import the `os` module. 

![imagen](https://user-images.githubusercontent.com/5055295/153058053-9f073d80-5885-481f-a973-f342a3c9afe3.png)

**Comment by Jean-Luc-Picard-2021** [comment]
Yes, yes and yes...
