### ISSUE TITLE
term_expansion not working for more than one rule?

### ISSUE THREAD

**Issue by gilbert** [tau-prolog/tau-prolog#296]
Take the following code:

```
:- op(1200, xfx, (<-)).

term_expansion((Head <- Body), (Head :- Body)).

term_expansion((bar :- Body), (bar2 :- Body)).

foo <- write(test1), nl, true.

bar :- write(test2), nl, true.
```

The following queries are expected to work:

```
?- foo.
test1
true.

?- bar2.
test2
true.
```

What happens instead (in [the sandbox](http://tau-prolog.org/sandbox/)):

1) On consult, an empty message is displayed:
<img width="456" alt="image" src="https://user-images.githubusercontent.com/17013/156407008-6ef7d126-4d56-48a0-9135-c33923375e7c.png">

2) Neither expansion works:

<img width="519" alt="image" src="https://user-images.githubusercontent.com/17013/156407203-839b358c-bc0f-4eac-95cd-90503b47702d.png">

**On the other hand,** if you comment out *one* of the `term_expansion` rules, then the *other* rule works (but consulting still gives an empty message).

**Comment by jariazavalverde** [comment]
I uploaded a fix, but further testing is needed. Let me know if you find another bug. 

![imagen](https://user-images.githubusercontent.com/5055295/156834616-d1d7706c-610f-40e9-9280-86f88fc966a6.png)

**Comment by gilbert** [comment]
Seems to be working great. Thank you!
