### ISSUE TITLE
"read(Response)" loops and never returns a value 

### ISSUE THREAD

**Issue by martinklein** [tau-prolog/tau-prolog#298]
In a well known example of a "flu_cold" expert system I am trying to read user input:

```
% Ask a question
ask(Question) :-
 write('Do you have the following symptom: '),
 write(Question),
 write('? '),
 read(Response),
 ( (Response == yes ; Response == y)  ->  assert(yes(Question)) ;  assert(no(Question)), fail).
```
It writes the questions but the read(Response) opens an Input pop-up where I can enter anything but when I press klick "Ok" the pop-up comes up again with an empty input field. When I then just click Ok it returns "end-of-file".

Many thanks for your suggestions. 

PS: also the "write" statements did not do anything originally. Then I found a suggestion to use this workaround:
```
:-use_module(library(js)).
write(X) :- apply(alert, [X], X).
```

**Comment by jariazavalverde** [comment]
- The `read/1` predicate reads the next Prolog term, and it must end in a full stop. So you must type `yes.`.
- The default output stream in browsers is `console.log`. You can use the `dom` module and open an HTML element as a stream to write in it, or use your workaround.
- The `assert/1` predicate doesn't exist: use `asserta/1` or `assertz/1` instead.
