### ISSUE TITLE
DCG translation not steadfast

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [tau-prolog/tau-prolog#308]
Was running this test case:
```
p --> \+ q.
q --> {write('did you call me?'), nl}.
```
In Tau Prolog 0.3.2 (beta) I get:
```
p([a],[]).
false.
```
On the other hand SWI-Prolog gives me:
```
?- p([a],[]).
did you call me?
false.
```

**Comment by Jean-Luc-Picard-2021** [comment]
I like how TauProlog translates (\+)/1, i.e. that it doesn't use
phrase/3 unlike what UWN proposes:
```
dcg_cbody(\+ GRBody, S0, S, ( \+ phrase(GRBody1,S0,_), S0 = S ), M) :-
module_call_qualified(M, GRBody, GRBody1). 
```
But I guess one can read off from UWNs translation how to
make it steadfast, i.e. the extra `S0 = S`.

**Comment by gilbert** [comment]
@Jean-Luc-Picard-2021 What's the definition of steadfast? I've tried looking it up before but couldn't get a clear answer.

**Comment by triska** [comment]
@gilbert: "steadfast" is hard to define in general. A "classical" example of a definition that is *not* steadfast is usually given for `max/3`, which we can *wrongly* define as:

<pre>
max(X, Y, X) :- X > Y, !.
max(_, Y, Y).
</pre>

With this definition, which seems to make intuitive sense, we have:

<pre>
<b>?- max(1, 0, X).</b>
   X = 1.
</pre>

It works as expected, right? But on the other hand, the maximum of 1 and 0 is unexpectedly 0 if we ask like this:

<pre>
<b>?- max(1, 0, 0).</b>
   true.
</pre>

The predicate is not *steadfast* in the sense that, by instantiating arguments in the query, **we can trick it to yield an answer that we actually did not intend to define**. The (1980's) textbook way to solve this issue in this concrete case is to *delay* the unification of `X` and the third argument to occur only *after* the `!/0`:

<pre>
max(X, Y, Z) :- X > Y, !, X = Z.
</pre>

It is clear that nobody wants to write such code and that moreover, nobody wants to risk running into such unexpected problems, and we would therefore of course simply define, via a single clause:

<pre>
max(X, Y, Z) :- Z #= max(X, Y).
</pre>

and thus get a shorter and significantly more general definition, at least as we reason about integers, as is normally also the case.

In the case under discussion, "steadfastness" is, somewhat analogously, a guarantee that certain parts of the grammar rule are executed *no matter the instantiation of arguments*: We cannot "trick" the definition to yield unexpected results by instantiating parts of the query.

**Comment by Jean-Luc-Picard-2021** [comment]
Steadfast in connection with DCG is defined in the DCG Draft.
