### ISSUE TITLE
DCG fix wrong

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [tau-prolog/tau-prolog#309]
Sorry for interupting again. I don't know how to re-open the old ticket,
so I made a new ticket here. Thats not the correct fix for:
https://github.com/tau-prolog/tau-prolog/issues/308#issuecomment-1118596127

> There seems to be a problem with the variables. It doesn't pick up _2 as the last variable 
in the head of p/2, but the transformation of the body is correct.

> % p/2
> p(_1,_1) :- \+ q(_1,_2).

Is core.js already out? You need to generate a `(=)/2` to make it steadfast. 
But if you change something with `_2` you break `(\+)/1` DCG.

**Comment by Jean-Luc-Picard-2021** [comment]
(\+)/1 is like in PEG grammar formalism:

Now you translate it into:
```
% p/2
p(_1,_2) :- \+ q(_1,_2).
````
So your fix made it worse....

**Comment by Jean-Luc-Picard-2021** [comment]
A reference implementation is here:
https://github.com/trealla-prolog/trealla/issues/549#issuecomment-1118519091

**Comment by jariazavalverde** [comment]
Ok, now it should be fixed.

```prolog
% p/2
p(_1,_3) :- \+ q(_1,_2), _1=_3.

% q/2
q(_4,_5) :- write('did you call me?'), nl, _4=_5.
```
