### ISSUE TITLE
Feature request, no prompt when there are no choice points

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [tau-prolog/tau-prolog#314]
When using the new REPL I get, it prompts 2 times:
```
$ node taupl
/* Tau Prolog new REPL */
?- X=a; X=b.
X = a ;
;
X = b.
;
false.
?- 
```
Many Prolog systems detect that the solution `X=b` doesn't leave any further
choice points, and then omit the second prompt:
```
/* SWI-Prolog */
?- X=a; X=b.
X = a ;
X = b.

?- 
```
Would it be possible to bring this feature to Tau Prolog?

**Comment by Jean-Luc-Picard-2021** [comment]
Inspecting the new taupl.js I get:

Somehow the `show` seems to already detect that there are no choice
points, since Tau Proog writes a period `X = b.`. But `next_answer` is
possibly too greedy in that it always calls action. Not sure.

**Comment by Jean-Luc-Picard-2021** [comment]
Ok, I made myself a new top-level:

Change 1: in taupl.js:
```
-     console.log(pl.format_answer(answer, session, {quoted: true}));
+     fs.writeSync(process.stdout.fd, pl.format_answer(answer, session, {quoted: true}));

        if(answer === false || pl.type.is_error(answer))
            callback();
+       else if (!(session.thread.points.length > 0))
+           callback();
        else
            action(callback);
````
Change 2: in core.js:
````
-				var delimiter = typeof thread === "undefined" || thread.points.length > 0 ? " ;" : "."; 
+				var delimiter = typeof thread === "undefined" || thread.points.length > 0 ? " " : ".\n";
````
Seems to work now:

[taupl.js.txt](https://github.com/tau-prolog/tau-prolog/files/8717675/taupl.js.txt)
[core.js.txt](https://github.com/tau-prolog/tau-prolog/files/8717677/core.js.txt)

![image](https://user-images.githubusercontent.com/95891213/169082280-e8d620d2-66bf-40c3-acb6-1af81c64eb61.png)

**Comment by jariazavalverde** [comment]
Done. Thanks for the improvement.
