### ISSUE TITLE
loading facts taking (much) longer in 0.3.3

### ISSUE THREAD

**Issue by josd** [tau-prolog/tau-prolog#316]
Loading https://gist.githubusercontent.com/josd/601ec656b9fd0981bff804ef634d8eba/raw/d0aa6b38e50f0a5c3aa05ab2aef42b07ae97fcbb/i20000.pl with tau-prolog@0.3.3 takes `sec=65.680` whereas it took `sec=0.970` with tau-prolog@0.3.2

**Comment by jariazavalverde** [comment]
Fixed. Clause indices were being recomputed from scratch every time a clause was loaded.

Thanks for the report.

**Comment by josd** [comment]
Thank you very much and now the extended deep taxonomy https://github.com/josd/eyebrow/blob/master/examples/edt.pl runs in a quite acceptable time
```
$ time node test.js examples/edt.pl
'http://example.org/ns#N100000'('http://example.org/ns#i100000') => true.

real    0m44.472s
user    1m7.346s
sys     0m3.739s
```
