### ISSUE TITLE
How getting all the sandbox output into html? 

### ISSUE THREAD

**Issue by joseph-vidal-rosset** [tau-prolog/tau-prolog#326]
Hello, 

 I do not find (or  I do not understand) how showing in html _all_ the output given in sandbox, including the result of write predicate . 
For example with fCube prover that is at the moment running online via SWI here [https://www.vidal-rosset.net/fCube/](url) , with  query `decide((p=>p)).`  I get in Tau Prolog sandbox the following correct output: 

> true

>> Input Formula:
>> F (p => p)
>> Sign Permanence tried,input formula equivalent to: 
>> F (p => p);
>> F->,Main SWFF: F (p => p)
>> T p;
>> F 1;
>> 1 search result = provable (fCube-4.1)

>parsing query: decide((p=>p)) ok!

My problem is that, if I follow for fCube the example of program given by Phil Zucker here [https://www.philipzucker.com/javascript-automated-proving/](url) , with this line of code: 

`function fillbox(e){
    console.log(e);
 document.getElementById("querybox").value = `provable((${htmlDecode(e.innerHTML)} ), Proof).`;
}`

 I do not succed to get as output in my html page anything else than the first line of the output in the sandbox, that is "true", and all the yellow part of the sandbox that gives the output of write predicate does not appear. 

I am sorry to ask this question at this place, but I find on the web neither Tau Prolog forum nor mailing list to get some help. 

Best wishes,

Jo.

**Comment by Jean-Luc-Picard-2021** [comment]
Try the return button.

**Comment by joseph-vidal-rosset** [comment]
> Try the return button.

?

**Comment by Jean-Luc-Picard-2021** [comment]
Try the return button. After the query.
If you didn't edit the query, and press return again, it will show more solutions:

![image](https://user-images.githubusercontent.com/95891213/182352441-84ca63ce-dad3-46db-b099-c826390ead8f.png)

**Comment by joseph-vidal-rosset** [comment]
> Press the return button on your keyboard. After the query. If you didn't edit the query, and press return again, it will show more solutions:

I get "false", that's it. My problem is getting into a html prover all the solution that is given in sandbox, including the output of write predicate. I do not know the javascript code to get it...

**Comment by jariazavalverde** [comment]
In Tau Prolog, you can open a regular HTML element as a stream. I think the best option is to write the output directly from Prolog.

```html
<div id="writeme"></div>
```

```prolog
:- use_module(library(dom)).

output :-
    get_by_id(writeme, WriteMe),
    open(WriteMe, write, Stream),
    write(Stream, hello),
    write(Stream, world).
```

**Comment by joseph-vidal-rosset** [comment]
> In Tau Prolog, you can open a regular HTML element as a stream. I think the best option is to write the output directly from Prolog.
> 
> ```
> <div id="writeme"></div>
> ```
> 
> ```prolog
> :- use_module(library(dom)).
> 
> output :-
>     get_by_id(writeme, WriteMe),
>     open(WriteMe, write, Stream),
>     write(Stream, hello),
>     write(Stream, world).
> ```

Many thanks. So, I do not know if it is correct, but to get all the written output,  I have only addedd 
`get_by_id(writeme, WriteMe),
    open(WriteMe, write, Stream), ` in the body of the clauses for decide/1 (i.e. intDecide/3) , without forgetting `:- use_module(library(dom)).` at the beginning of the prolog program. But I get this error: 

> uncaught exception: error(existence_error(procedure,get_by_id/2),intDecide/3)

I add that Tau Prolog is called by:

`<script src="https://cdn.jsdelivr.net/npm/tau-prolog@0.3.3/modules/core.min.js"></script> <script src="https://cdn.jsdelivr.net/npm/tau-prolog@0.3.3/modules/lists.js"></script><script src="https://cdn.jsdelivr.net/npm/tau-prolog@0.3.3/modules/js.js"></script>`

**Comment by joseph-vidal-rosset** [comment]
> In Tau Prolog, you can open a regular HTML element as a stream. I think the best option is to write the output directly from Prolog.
> 
> ```
> <div id="writeme"></div>
> ```
> 
> ```prolog
> :- use_module(library(dom)).
> 
> output :-
>     get_by_id(writeme, WriteMe),
>     open(WriteMe, write, Stream),
>     write(Stream, hello),
>     write(Stream, world).
> ```

Thanks. My first test from what you suggested was completely incorrect. In fact I confess that I do not see how to do... :(

**Comment by joseph-vidal-rosset** [comment]
Note that the same problem exists with  time/1 : how is it possible to get the result of statistics or time in an html page where a Tau Prolog program is running? That is the case for example of this prover online [https://www.vidal-rosset.net/sequent_calculus_prover_with_antisequents_for_classical_propositional_logic.html](url)  where 
`provable(F,P):-
        time(prove([]>[F],P)).`
the value of time is given by Tau Prolog (it appears in the sandox) but not on the web page, unfortunately. :(

**Comment by jariazavalverde** [comment]
You can set the output with `set_output/2`:

```prolog
:- use_module(library(dom)).

main(Goal) :-
    get_by_id(writeme, WriteMe),
    open(WriteMe, write, Stream),
    set_output(Stream),
    call(Goal).
```
Thus, all output produced by your goal is redirected to the HTML element with id `writeme`.

**Comment by joseph-vidal-rosset** [comment]
Many thanks José, your code is clear and very helpful ! It works now: the value of time appears now  <a href="https://www.vidal-rosset.net/sequent_calculus_prover_with_antisequents_for_classical_propositional_logic.html">in this Tau-Prolog prover</a>. I guess it is in msec; that's why I added write(' msec.').  I will try to publish fCube with Tau-Prolog tomorrow, but I think that it will be easy now. I will close this thread then and I will thank you again.  All the best !

**Comment by joseph-vidal-rosset** [comment]
Hello,
As I promised, I'm trying to publish <a href="https://www.vidal-rosset.net/fCube">FCube: An Efficient Prover for Intuitionistic Propositional Logic </a> with Tau Prolog. This prover runs presently with SWI and php. You can see on this webpage that there is no difference with the output and emacs's or ones of another shell terminal. For 
example, the disproof of `(a=>b) ` : 

> Input Formula:
>  F (a => b)
> Sign Permanence tried,input formula equivalent to: 
   T a;
   FC b;
 > 1 search result = unprovable (fCube-4.1)
*** The Counter Model (see also the prolog term ) ***
-- root --
   T a;
   FC b;
-- end world --
*** Prolog term of the countermodel ***
[swff(t,a),swff(fc,b)]

By contrast, the html output via Tau-Prolog provides unwelcome translations, for the same formula, I get: 

> Input Formula: F (a =& Sign Permanence tried,input formula equivalent to: T a; FC b; 1search result = unprovable (fCube-4.1) *** The Counter Model (see also the prolog term ) *** -- root -- T a; FC b; -- end world -- *** Prolog term of the countermodel *** [swff(t,a),swff(fc,b)] 82.0 msec.

I've tried to use `<div id="writeme"><pre> </pre></div>`  to get the output into a verbatim block, but it does not work. I know that a solution would be to translate every `write('  ')` occurrence with html code inside, but I wonder if a better and simpler solution exists... 
Suggestions are welcome.

**Comment by jariazavalverde** [comment]
In order to fix line breaks, try to apply the following style to the output element:

```css
#writeme {
    white-space: pre;
}
```

**Comment by joseph-vidal-rosset** [comment]
Many thanks ! I will try this solution and I'll tell you the result. But not before 10 days: I am in vacation and without my computer, for a real break. We stay in touch.
Best wishes, 
Jo.

**Comment by joseph-vidal-rosset** [comment]
Hello. Added in my css file, the code 
`#writeme {
    white-space: pre;
}`
works _almost_ fine. 
This one : 
`#writeme {
  white-space: pre-wrap;
}`
works even better, or still this last one:
`#writeme {
  overflow-x: auto;
  white-space: pre-wrap;
  word-wrap: break-word;
  font-size: 20px;
  color : red
}
pre {
  overflow-x: auto;
}`

BUT, I do not find the solution to get exactly the output given in emacs or in shell. The problem is for right arrow, for example, with this input 
`Classical De Morgan's Law : ~((a & b)) => (~ a | ~b) `
here is the first line of the output just after "true":
`Input Formula:
F (~(a&am(~a | ~b))`
:-1: 
and I do not find the solution...

**Comment by Jean-Luc-Picard-2021** [comment]
You need to XML entity escape & and > , the later appears in =>.  See here:

What characters do I need to escape in XML documents?
https://stackoverflow.com/a/1091953/17524790

**Comment by joseph-vidal-rosset** [comment]
Thanks !

**Comment by Jean-Luc-Picard-2021** [comment]
It, depends how you send the output to the
HTML page. There are two options basically:

Option 1:
element.innerText += output

Option 2:
element.innerHTML += output

If Tau Prolog uses Option 1 or your code uses
Option 1, you don't need to do anything, then
output can for example be "a => b", the ">" gets

not interpreted. If Tau Prolog uses Option 2 or your
 code uses Option 2, you need to do XML Escape,
and replace ">" by "&lt;" so that it doesn't get

interpreted. From the bug here, it seems that
Option 2  is somewhere used:

> The problem is for right arrow, for example, with this input
> `Classical De Morgan's Law : ~((a & b)) => (~ a | ~b) `
> here is the first line of the output just after "true":
> `Input Formula: F (~(a&am(~a | ~b))`

**Comment by joseph-vidal-rosset** [comment]
Yes, it is option 2. 
But I put the java script code that you send to me to do it in my webpage, that is to say:

`export function xml_escape(str) {
    let buf = "";
    let last = 0;
    let i = 0;
    while (i < str.length) {
        let ch = str.codePointAt(i);
        switch (ch) {
            case 34: // "
                buf += str.slice(last, i) + "&quot;";
                last = i + 1;
                break;
            case 38: // &
                buf += str.slice(last, i) + "&amp;";
                last = i + 1;
                break;
            case 60: // <
                buf += str.slice(last, i) + "&lt;";
                last = i + 1;
                break;
            case 62: // >
                buf += str.slice(last, i) + "&gt;";
                last = i + 1;
                break;
            default:
                break;
        }
        i += char_count(ch);
    }
    if (last !== 0) {
        buf += str.slice(last);
        return buf;
    } else {
        return str;
    }
}`

but the result did not change...  :(

**Comment by Jean-Luc-Picard-2021** [comment]
Better put the Prolog code, and use it before you call write/2.
So instead of this here:
```
    get_by_id(writeme, WriteMe),
    open(WriteMe, write, Stream),
    set_output(Stream),
    ...
    write(Formula)
```
You need to do:
```
    get_by_id(writeme, WriteMe),
    open(WriteMe, write, Stream),
    set_output(Stream),
    ...
    term_atom(Formula, FormulaAtom),
    xml_ecape(FormulaAtom, FormulaEscaped),
    write(FormulaEscaped)
```
Or in words, you need to XML Escape the output.

**Comment by Jean-Luc-Picard-2021** [comment]
The name XML Escape stems from the 5 predefined character entities in XML:

Name | Character | Unicode code point (decimal) | Standard
-- | -- | -- | --
quot | " | U+0022 (34) | XML 1.0
amp | & | U+0026 (38) | XML 1.0
apos | ' | U+0027 (39) | XML 1.0
lt | < | U+003C (60) | XML 1.0
gt | > | U+003E (62) | XML 1.0

https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#List_of_predefined_entities_in_XML

**Comment by joseph-vidal-rosset** [comment]
Thanks for all. 
It is really complicated. 
Probably a simpler solution would be to change the code of writing operators in fCube...

**Comment by Jean-Luc-Picard-2021** [comment]
Its from 1995, I always though the world was simple then?

**Comment by joseph-vidal-rosset** [comment]
> It, depends how you send the output to the HTML page. There are two options basically:
> 
>     * **Option 1:**
>       element.innerText += output
> 
>     * **Option 2:**
>       element.innerHTML += output
> 
> 
> If Tau Prolog uses Option 1 or your code uses Option 1, you don't need to do anything, then output can for example be `"... a => b ..."`, the ">" gets
> 
> not interpreted. 

I replaced everywhere in tau-prolog.js as in my html page `innerHTML`  by `innerText`  and the problem is completely solved !  Many thanks ! 

Is this a good solution for all Tau Prolog programs? This question is for the developers.

**Comment by Jean-Luc-Picard-2021** [comment]
Where is a link to your final result. The drawback, you
need a custom dom.js, so everytime Tau Prolog

rolls out a new dom.js, you need to manually adapt it.
So this is only a workaround, no permanent

solution so far. You need to talk with the Tau Prolog
core team developers more.

**Comment by joseph-vidal-rosset** [comment]
> Where is a link to your final result

![Capture d’écran_2022-09-01_13-13-19](https://user-images.githubusercontent.com/8275626/187901036-1e1c2038-ab55-42a0-8083-869940a2828f.png)

**Comment by Jean-Luc-Picard-2021** [comment]
I mean a link on https://www.vidal-rosset.net/
