### ISSUE TITLE
feature request lookahead (\+)/1 construct in DCG

### ISSUE THREAD

**Issue by jburse** [tau-prolog/tau-prolog#42]
Was playing around with DCG in Tau Prolog. Found a small
gap. It seems that (\+)/1 is not yet translated. I made the following test:

![grafik](https://user-images.githubusercontent.com/5411487/43357733-601cbb60-9286-11e8-96b1-51281b1648bd.png)

**Comment by jburse** [comment]
The DCG draft says that it is implementation dependent:

   ISO/IEC DTR 13211{3:2006 Definite clause grammar rules
   Editor: Jonathan Hodgson November 10, 2015
   % dcg_constr(\+ _). % 7.14.11 - not (existence implementation dep.)
   https://www.complang.tuwien.ac.at/ulrich/iso-prolog/dcgs/dcgsdraft-2015-11-10.pdf

But many Prolog systems (like SWI7, GNU, etc..) already implement it, and 
already do a full translation, not only a translation to phrase/3 as in the 
above draft. Here is the same example in GNU Prolog 1.4.5:

![grafik](https://user-images.githubusercontent.com/5411487/43357768-e020250e-9286-11e8-9273-c469c42346b1.png)

**Comment by jariazavalverde** [comment]
Added! Thanks for your report.

![dcg](https://user-images.githubusercontent.com/5055295/73372885-3216eb80-42b8-11ea-8b20-857b900366a3.png)
