### ISSUE TITLE
Feature Request consult/1

### ISSUE THREAD

**Issue by PaulBrownMagic** [tau-prolog/tau-prolog#87]
When using `session.consult` we either have to provide a string or an id to a script tag. Unfortunately most browsers wont load a script tag that's not of type "text/javascript", such as:

```<script type="text/prolog" src="/static/pl/doge.pl"></script>```

I work around this by using a `XMLHttpRequest` to fetch the file from the server and feed that into `session.consult`, but this is messy when there's more than one file to consult because it's a callback function. This means there's no good way to say "when you've finished loading everything then do this query".

What would be really nice is:
```
<script>
const session = pl.create()
session.consult(":- consult('/static/pl/doge.pl').")
session.query("init.")
session.answer((a)=>{})
</script>
```

`consult/1` should first check for an id on the page and consult that. If one isn't found it should send a XMLHttpRequest to the provided URL and consult that. Because it's now part of the Prolog program, I'm hoping that means the query won't occur until after it's finished loading.

The advantage of including it in the Prolog rather than the JavaScript would be that it's easier to compose Prolog programs of parts within the program seen as that is what we are editing when developing the program. However, it may be possible/easier to simply add the XMLHttpRequest behaviour to `session.consult`. Furthermore, if this is the case it might be possible to make `consult/1` a proxy to `session.consult`?

**Comment by matteoredaelli** [comment]
Hello

Any news about this feature? will it be implemented?

Regards
Matteo

**Comment by jariazavalverde** [comment]
I just added a `consult/1` built-in predicate (v0.2.81) as a proxy of `Session.prototype.consult`. Its behavior is as follows:

1. Search for a script with that id (only in browser).
2. Search for a file with that name (only in node).
3. (Synchronous) HTTP request to that path.
4. Consult the raw content.
