### ISSUE TITLE
feature request version/0 predicate

### ISSUE THREAD

**Issue by jburse** [tau-prolog/tau-prolog#92]
Hi,

I have a feature request. When working with Tau Prolog I would like to know which version I am working with. There is a quasi standard that a Prolog system provides a predicate version/0. At least I find 3 Prolog systems that do that:

SWI-Prolog has it:
![image](https://user-images.githubusercontent.com/5411487/66846623-5a314780-ef72-11e9-9594-9cc1e94fc749.png)

YAP Prolog has it:
![image](https://user-images.githubusercontent.com/5411487/66846657-674e3680-ef72-11e9-9f76-699877fea56e.png)

My system has it:
![image](https://user-images.githubusercontent.com/5411487/66846696-7cc36080-ef72-11e9-9809-04f28bf00712.png)

But how should this be done in Tau Prolog. Does it have write/1 and nl/0 already somehow?

Bye

**Comment by jariazavalverde** [comment]
Yes. Tau Prolog already has all the I/O standard predicates, for both browsers and Node.js, so we can add that predicate. Meanwhile, you can type `pl.version` in the terminal to see the current version.

![version](https://user-images.githubusercontent.com/5055295/66851407-fbbc9700-ef7a-11e9-9693-256e053c6245.png)
