### ISSUE TITLE
Limit/stack exceeded when resolving sub-sub-element of list

### ISSUE THREAD

**Issue by koxu1996** [tau-prolog/tau-prolog#94]
I was unable to run my program with _tau-prolog_ - stack limit exceeded - so I investigated the problem. I found there is simple predicate that cause infinite loop without reason:
`nth0(0, [[1,2],[3,4]], List1), nth0(0, List1, Result).`
Sandbox screenshot:
![2019-12-01-001958_grim](https://user-images.githubusercontent.com/6506780/69907164-53e71580-13d0-11ea-8fbe-0df6f98334cb.png)

**Comment by jariazavalverde** [comment]
There was a bug in the if-then-else (->;) predicate. Thanks for your report!
