### ISSUE TITLE
get_time/1 predicate missing

### ISSUE THREAD

**Issue by zavalyshyn** [tau-prolog/tau-prolog#95]
Hi,

I've noticed that [`get_time/1`](https://www.swi-prolog.org/pldoc/man?predicate=get_time%2f1) predicate is missing from the built-in modules. 

Whenever I try to use it I get `error(existence_error(procedure, '/'(get_time, 1))`

Was it accidentally left out or it was intentional? I suspect not many users rely on it. But I do.

Thanks

**Comment by jariazavalverde** [comment]
`get_time/1` isn't an ISO standard predicate. Anyway, I just added it 71dc61a7c53f7a2402e094b270039e494a5cacbd (v0.2.81) for compatibility with SWI-Prolog.

Thanks for your report.
