### ISSUE TITLE
Add ability to submit non-form data through ajax/4

### ISSUE THREAD

**Issue by neetle** [tau-prolog/tau-prolog#96]
Was trying to interact with an API that disallows the use of form submission to submit. I was using `body/1` to submit, and it only allows the use of form data. 

If possible, could it default to using `JSON.stringify` or similar to encode the data when the [Content-Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) is set to `application/json`?

**Comment by jariazavalverde** [comment]
You can use `json_prolog/2` and `json_atom/2` to convert json objects to prolog data (and vice versa).

**Comment by neetle** [comment]
From what I understand, the code that sends the request always serialises
the JSON object as a FormData unless it is a HTML element.

Some APIs don't support FormData for their endpoints, limiting the amount
of reach Tau can have on the front end without having to duplicate
functions.

For example, I'd love to be able to use this with some GraphQL endpoints,
but they only support raw JSON in the body iirc and choke on the FormData
that ajax/4 submits.

I'm happy to submit a PR once we spec this out.

**Comment by jariazavalverde** [comment]
I just added the option to send atoms in the body of `ajax/4`. Now you can send JSON data in this way:
```prolog
json_prolog(JSON, [a-1, b-2]), json_atom(JSON, Atom), ajax(post, URL, Response, [body(Atom)]).
```

You can try it in our sandbox by sending JSON data to http://tau-prolog.org/files/sample/post_json.php:

![json](https://user-images.githubusercontent.com/5055295/73143836-fd7c1780-409e-11ea-9262-a016161f86c4.png)
